In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("titanic.csv")

In [4]:
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [5]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)


In [6]:
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [7]:
inputs=df.drop('Survived',axis='columns')
target=df.Survived

In [8]:
dummies=pd.get_dummies(inputs.Sex)
dummies=dummies.astype(int)
dummies.head(3)

female  male
0       0     1
1       1     0
2       1     0

In [9]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

In [10]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [11]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [12]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [13]:

inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)


In [15]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [16]:
model.fit(X_train,y_train)

GaussianNB()

In [17]:
model.score(X_test,y_test)

0.7761194029850746

In [18]:
X_test[0:10]

Pclass   Age      Fare  female
439       2  31.0   10.5000       0
106       3  21.0    7.6500       1
534       3  30.0    8.6625       1
308       2  30.0   24.0000       0
875       3  15.0    7.2250       1
74        3  32.0   56.4958       0
114       3  17.0   14.4583       1
668       3  43.0    8.0500       0
660       1  50.0  133.6500       0
716       1  38.0  227.5250       1

In [19]:
y_test[0:10]

439    0
106    1
534    0
308    0
875    1
74     1
114    0
668    0
660    1
716    1
Name: Survived, dtype: int64

In [20]:
model.predict(X_test[0:10])

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 1])

In [21]:
model.predict_proba(X_test[:10])

array([[9.30854127e-01, 6.91458731e-02],
       [3.67135575e-01, 6.32864425e-01],
       [3.97759358e-01, 6.02240642e-01],
       [9.28293629e-01, 7.17063715e-02],
       [3.35634166e-01, 6.64365834e-01],
       [9.30681240e-01, 6.93187595e-02],
       [3.52573331e-01, 6.47426669e-01],
       [9.66544542e-01, 3.34554576e-02],
       [5.12637479e-03, 9.94873625e-01],
       [9.93754067e-11, 1.00000000e+00]])

In [22]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.728     , 0.808     , 0.768     , 0.7983871 , 0.77419355])